const translations = {
  el: {
    topStrip: 'Επείγουσα βλάβη; Μιλήστε απευθείας με τεχνικό.', navHome: 'Αρχική', navAbout: 'Σχετικά', navWork: 'Η δουλειά μας', navContact: 'Επικοινωνία', callShort: 'Κλήση τώρα', openMenu: 'Άνοιγμα μενού',
    heroEyebrow: 'Υδραυλικός 24/7 • Αθήνα & προάστια', heroTitle: 'Όταν τρέχει νερό, θέλετε άνθρωπο που απαντάει — και λύνει.', heroCopy: 'Το To Ydravliko αναλαμβάνει επείγουσες βλάβες, θερμοσίφωνες, αποφράξεις και υδραυλικές εγκαταστάσεις με γρήγορη διάγνωση, καθαρή εργασία και ξεκάθαρη ενημέρωση πριν ξεκινήσει οτιδήποτε.', callNow: 'Καλέστε για άμεση βοήθεια', requestVisit: 'Στείλτε αίτημα', proofRating: 'μέση αξιολόγηση', proofReviews: 'κριτικές πελατών', proofHours: 'επείγουσα ανταπόκριση', responseTitle: 'Πρώτα διάγνωση, μετά λύση', responseCopy: 'Ξέρετε τι χρειάζεται πριν πληρώσετε.',
    servicesEyebrow: 'Υπηρεσίες', servicesTitle: 'Δεν φτιάχνουμε απλώς σωλήνες. Σταματάμε την αναστάτωση.', servicesIntro: 'Κάθε υπηρεσία είναι σχεδιασμένη για να κλείνει το πρόβλημα με ασφάλεια, καθαρότητα και πρακτικές συμβουλές πρόληψης.', service1Title: 'Διαρροές & σπασμένοι σωλήνες', service1Copy: 'Εντοπίζουμε την αιτία, περιορίζουμε τη ζημιά και αποκαθιστούμε τη ροή με υλικά κατάλληλα για το σημείο.', service2Title: 'Θερμοσίφωνες & ζεστό νερό', service2Copy: 'Έλεγχος, αντικατάσταση, σύνδεση και επισκευή ηλεκτρικών ή ηλιακών θερμοσιφώνων.', service3Title: 'Μπάνια, κουζίνες & μερεμέτια', service3Copy: 'Μπαταρίες, σιφώνια, λεκάνες, νιπτήρες, παροχές πλυντηρίου και μικρές ή μεγάλες εγκαταστάσεις.', learnMore: 'Μάθετε περισσότερα',
    processEyebrow: 'Πώς δουλεύουμε', processTitle: 'Απλή διαδικασία, χωρίς εκπλήξεις.', processIntro: 'Ο πελάτης πρέπει να ξέρει ποιος έρχεται, τι θα ελέγξει και τι θα κοστίσει πριν προχωρήσει.', step1Title: 'Μας περιγράφετε τη βλάβη', step1Copy: 'Τηλέφωνο ή φόρμα με φωτογραφίες/λεπτομέρειες όταν υπάρχουν.', step2Title: 'Γίνεται διάγνωση στον χώρο', step2Copy: 'Ελέγχουμε αιτία, πρόσβαση, υλικά και πιθανές εναλλακτικές.', step3Title: 'Συμφωνούμε λύση', step3Copy: 'Ξεκάθαρη ενημέρωση πριν ξεκινήσει η εργασία.', step4Title: 'Παραδίδουμε καθαρά', step4Copy: 'Δοκιμή, καθαρισμός και οδηγίες για να αποφύγετε επανάληψη.', areasEyebrow: 'Περιοχές', areasTitle: 'Εξυπηρέτηση σε όλη την Αθήνα.', areasCopy: 'Κέντρο, βόρεια, νότια, δυτικά και ανατολικά προάστια, με προτεραιότητα σε επείγουσες διαρροές και βλάβες που μπορούν να προκαλέσουν ζημιά.', testimonialsEyebrow: 'Τι εκτιμούν οι πελάτες', testimonialsTitle: 'Αμεσότητα, συνέπεια και άνθρωποι που αφήνουν τον χώρο καθαρό.', review1: 'Ήρθε στην ώρα του, εξήγησε τι έφταιγε και η διαρροή σταμάτησε χωρίς να γεμίσει το σπίτι αναστάτωση.', review2: 'Άμεση ανταπόκριση σε βλάβη θερμοσίφωνα. Καθαρή δουλειά και λογική τιμή.', review3: 'Επαγγελματική συμπεριφορά από το τηλέφωνο μέχρι την παράδοση. Θα τους ξανακαλέσω.', ctaEyebrow: 'Μην το αφήνετε να μεγαλώσει', ctaTitle: 'Μια μικρή διαρροή μπορεί να γίνει ακριβή ζημιά.', ctaCopy: 'Καλέστε τώρα για άμεση εκτίμηση ή στείλτε το αίτημά σας και θα σας απαντήσουμε σύντομα.', ctaButton: 'Κλείστε επίσκεψη', footerCopy: 'Υδραυλικές εργασίες, επείγουσες βλάβες και εγκαταστάσεις.',
    aboutEyebrow: 'Σχετικά με εμάς', aboutTitle: 'Ηρεμία για τον πελάτη, τεχνική ακρίβεια για τη βλάβη.', aboutIntro: 'Το To Ydravliko δημιουργήθηκε για ανθρώπους που θέλουν γρήγορη απάντηση, καθαρή εξήγηση και εργασία που δεν χρειάζεται δεύτερη επίσκεψη για το ίδιο πρόβλημα.', storyEyebrow: 'Η φιλοσοφία μας', storyTitle: 'Πρώτα καταλαβαίνουμε το πρόβλημα. Μετά προτείνουμε λύση.', storyCopy: 'Σε κάθε επίσκεψη ελέγχουμε την πραγματική αιτία, όχι μόνο το εμφανές σύμπτωμα. Έτσι μειώνεται ο κίνδυνος να επιστρέψει η διαρροή, το βούλωμα ή η δυσλειτουργία λίγες μέρες μετά.', stat1: 'επείγουσα υποστήριξη', stat2: 'κριτικές εμπιστοσύνης', stat3: 'μέση αξιολόγηση', valueTitle1: 'Καθαρή ενημέρωση', valueCopy1: 'Σας λέμε τι βλέπουμε, τι προτείνουμε και ποια επιλογή έχει νόημα για τον χώρο σας.', valueTitle2: 'Σεβασμός στον χώρο', valueCopy2: 'Προστατεύουμε επιφάνειες όπου χρειάζεται και αφήνουμε το σημείο όσο πιο τακτοποιημένο γίνεται.', valueTitle3: 'Λύσεις με διάρκεια', valueCopy3: 'Χρησιμοποιούμε κατάλληλα υλικά και τεχνικές ώστε η επισκευή να μη λειτουργεί σαν προσωρινό μπάλωμα.', promiseEyebrow: 'Η υπόσχεσή μας', promiseTitle: 'Αν δεν χρειάζεται να γίνει κάτι, θα σας το πούμε.', promiseCopy: 'Η εμπιστοσύνη χτίζεται όταν ο τεχνικός δεν υπερβάλλει. Προτείνουμε απαραίτητες εργασίες, εξηγούμε εναλλακτικές και κρατάμε τον πελάτη ενήμερο από την αρχή μέχρι το τέλος.',
    workEyebrow: 'Η δουλειά μας', workTitle: 'Ολοκληρωμένες υδραυλικές υπηρεσίες, όχι πρόχειρες λύσεις.', workIntro: 'Από επείγουσα διαρροή μέχρι εγκατάσταση μπάνιου, η εργασία οργανώνεται με διάγνωση, σωστά υλικά, δοκιμή και καθαρή παράδοση.', work1Title: 'Διαρροές', work1Copy: 'Εντοπισμός αιτίας, αντικατάσταση τμήματος σωλήνα, στεγανοποίηση και έλεγχος πίεσης.', work2Title: 'Αποφράξεις', work2Copy: 'Αποκατάσταση ροής σε σιφώνια, νεροχύτες, νιπτήρες και αποχετεύσεις με προσοχή στις σωληνώσεις.', work3Title: 'Θερμοσίφωνες', work3Copy: 'Έλεγχος αντίστασης, θερμοστάτη, ασφαλιστικού, σύνδεση και αντικατάσταση μονάδας.', work4Title: 'Ανακαινίσεις', work4Copy: 'Παροχές, αποχετεύσεις, είδη υγιεινής, μπαταρίες και συντονισμός για καθαρό αποτέλεσμα.', detail1Title: 'Τι ελέγχουμε', detail1a: 'Πίεση και σταθερότητα ροής', detail1b: 'Φθορές σε εμφανή και κρυφά σημεία', detail1c: 'Σωστή λειτουργία βανών και ασφαλιστικών', detail2Title: 'Τι παραδίδουμε', detail2a: 'Δοκιμασμένη επισκευή', detail2b: 'Καθαρό σημείο εργασίας', detail2c: 'Συμβουλές πρόληψης και χρήσης', detail3Title: 'Πότε να καλέσετε άμεσα', detail3a: 'Νερό κοντά σε ηλεκτρικά', detail3b: 'Πτώση πίεσης ή συνεχής υγρασία', detail3c: 'Θερμοσίφωνας που στάζει ή ρίχνει ασφάλεια',
    contactEyebrow: 'Επικοινωνία', contactTitle: 'Στείλτε τη βλάβη. Θα σας απαντήσουμε με ξεκάθαρο επόμενο βήμα.', contactIntro: 'Για νερά που τρέχουν, θερμοσίφωνα που στάζει ή βλάβη που δεν περιμένει, προτιμήστε τηλεφωνική κλήση. Για μη επείγοντα, συμπληρώστε τη φόρμα.', nameLabel: 'Ονοματεπώνυμο', phoneLabel: 'Τηλέφωνο', emailLabel: 'Email', serviceLabel: 'Τι χρειάζεστε;', serviceOptionLeak: 'Διαρροή / βλάβη', serviceOptionBlockage: 'Απόφραξη', serviceOptionHeater: 'Θερμοσίφωνας', serviceOptionRenovation: 'Μπάνιο / κουζίνα', serviceOptionOther: 'Άλλο', urgencyLabel: 'Πόσο επείγον είναι;', urgencyNow: 'Επείγον / σήμερα', urgencySoon: 'Μέσα στις επόμενες ημέρες', urgencyQuote: 'Θέλω προσφορά', messageLabel: 'Περιγραφή προβλήματος', submitButton: 'Στείλτε αίτημα', urgentEyebrow: 'Άμεση επικοινωνία', directTitle: 'Για επείγον, καλέστε τώρα.', hoursText: '24/7 για επείγουσες βλάβες.', areaText: 'Αθήνα και προάστια.', supabaseText: 'Η φόρμα κρατά καθαρό payload για μελλοντική Supabase Edge Function αποστολής email.', faqEyebrow: 'Συχνές ερωτήσεις', faqTitle: 'Πριν καλέσετε', faq1Q: 'Τι να κάνω αν τρέχει πολύ νερό;', faq1A: 'Κλείστε την κεντρική βάνα αν μπορείτε με ασφάλεια και καλέστε μας. Αν υπάρχει νερό κοντά σε ρεύμα, αποφύγετε την επαφή.', faq2Q: 'Μπορώ να στείλω φωτογραφίες;', faq2A: 'Στη μελλοντική σύνδεση Supabase μπορεί να προστεθεί upload. Προς το παρόν, περιγράψτε το σημείο και θα σας καθοδηγήσουμε τηλεφωνικά.', faq3Q: 'Δίνετε εκτίμηση πριν την εργασία;', faq3A: 'Ναι, μετά τη διάγνωση εξηγούμε τις επιλογές και το κόστος πριν ξεκινήσει η επισκευή.', formSuccess: 'Το αίτημα καταγράφηκε τοπικά. Το επόμενο βήμα είναι η σύνδεση με Supabase για email στον ιδιοκτήτη.'
  },
  en: {
    topStrip: 'Emergency issue? Speak directly with a technician.', navHome: 'Home', navAbout: 'About', navWork: 'Our work', navContact: 'Contact', callShort: 'Call now', openMenu: 'Open menu',
    heroEyebrow: '24/7 plumber • Athens & suburbs', heroTitle: 'When water is running, you need someone who answers — and solves it.', heroCopy: 'To Ydravliko handles emergencies, water heaters, blockages, and installations with fast diagnosis, clean work, and clear information before anything starts.', callNow: 'Call for immediate help', requestVisit: 'Send request', proofRating: 'average rating', proofReviews: 'customer reviews', proofHours: 'emergency response', responseTitle: 'Diagnosis first, solution next', responseCopy: 'Know what is needed before you pay.',
    servicesEyebrow: 'Services', servicesTitle: 'We do not just fix pipes. We stop the disruption.', servicesIntro: 'Every service is designed to close the problem safely, cleanly, and with practical prevention advice.', service1Title: 'Leaks & broken pipes', service1Copy: 'We find the cause, limit the damage, and restore flow with materials suitable for the location.', service2Title: 'Water heaters & hot water', service2Copy: 'Inspection, replacement, connection, and repair of electric or solar water heaters.', service3Title: 'Bathrooms, kitchens & repairs', service3Copy: 'Faucets, drains, toilets, sinks, washing machine supplies, and small or large installations.', learnMore: 'Learn more',
    processEyebrow: 'How we work', processTitle: 'A simple process, with no surprises.', processIntro: 'Customers should know who is coming, what will be checked, and what it will cost before moving ahead.', step1Title: 'You describe the issue', step1Copy: 'Phone or form with photos/details when available.', step2Title: 'On-site diagnosis', step2Copy: 'We check the cause, access, materials, and possible alternatives.', step3Title: 'We agree on the solution', step3Copy: 'Clear information before work begins.', step4Title: 'Clean handover', step4Copy: 'Testing, cleanup, and guidance to avoid repeat issues.', areasEyebrow: 'Areas', areasTitle: 'Serving all of Athens.', areasCopy: 'Center, north, south, west, and east suburbs, with priority for urgent leaks and failures that can cause damage.', testimonialsEyebrow: 'What customers value', testimonialsTitle: 'Fast response, reliability, and people who leave the space clean.', review1: 'Arrived on time, explained the cause, and stopped the leak without turning the home upside down.', review2: 'Fast response for a water-heater issue. Clean work and fair price.', review3: 'Professional behavior from the phone call to handover. I would call them again.', ctaEyebrow: 'Do not let it grow', ctaTitle: 'A small leak can become expensive damage.', ctaCopy: 'Call now for quick guidance or send your request and we will reply soon.', ctaButton: 'Book a visit', footerCopy: 'Plumbing work, emergency repairs, and installations.',
    aboutEyebrow: 'About us', aboutTitle: 'Calm for the customer, technical accuracy for the issue.', aboutIntro: 'To Ydravliko was built for people who want a fast answer, a clear explanation, and work that does not need a second visit for the same problem.', storyEyebrow: 'Our philosophy', storyTitle: 'First we understand the problem. Then we recommend a solution.', storyCopy: 'On every visit we check the real cause, not just the visible symptom. This reduces the risk of the leak, blockage, or malfunction returning a few days later.', stat1: 'emergency support', stat2: 'trusted reviews', stat3: 'average rating', valueTitle1: 'Clear information', valueCopy1: 'We tell you what we see, what we recommend, and which option makes sense for your space.', valueTitle2: 'Respect for your space', valueCopy2: 'We protect surfaces where needed and leave the work area as tidy as possible.', valueTitle3: 'Lasting solutions', valueCopy3: 'We use suitable materials and methods so the repair is not a temporary patch.', promiseEyebrow: 'Our promise', promiseTitle: 'If something does not need to be done, we will tell you.', promiseCopy: 'Trust is built when a technician does not exaggerate. We recommend necessary work, explain alternatives, and keep the customer informed from start to finish.',
    workEyebrow: 'Our work', workTitle: 'Complete plumbing services, not quick patches.', workIntro: 'From urgent leaks to bathroom installation, the work is organized with diagnosis, proper materials, testing, and clean handover.', work1Title: 'Leaks', work1Copy: 'Cause detection, pipe-section replacement, sealing, and pressure checks.', work2Title: 'Blockages', work2Copy: 'Flow restoration in floor drains, sinks, basins, and waste lines with care for the pipework.', work3Title: 'Water heaters', work3Copy: 'Heating element, thermostat, safety valve checks, connection, and unit replacement.', work4Title: 'Renovations', work4Copy: 'Water supplies, drainage, sanitary ware, faucets, and coordination for a clean result.', detail1Title: 'What we check', detail1a: 'Pressure and flow stability', detail1b: 'Wear in visible and hidden points', detail1c: 'Proper operation of valves and safety parts', detail2Title: 'What we deliver', detail2a: 'Tested repair', detail2b: 'Clean work area', detail2c: 'Prevention and usage advice', detail3Title: 'When to call immediately', detail3a: 'Water near electrical points', detail3b: 'Pressure drop or constant moisture', detail3c: 'Water heater dripping or tripping power',
    contactEyebrow: 'Contact', contactTitle: 'Send the issue. We will reply with a clear next step.', contactIntro: 'For running water, a dripping water heater, or an issue that cannot wait, call instead. For non-urgent requests, fill in the form.', nameLabel: 'Full name', phoneLabel: 'Phone', emailLabel: 'Email', serviceLabel: 'What do you need?', serviceOptionLeak: 'Leak / repair', serviceOptionBlockage: 'Blockage', serviceOptionHeater: 'Water heater', serviceOptionRenovation: 'Bathroom / kitchen', serviceOptionOther: 'Other', urgencyLabel: 'How urgent is it?', urgencyNow: 'Urgent / today', urgencySoon: 'In the next few days', urgencyQuote: 'I need a quote', messageLabel: 'Problem description', submitButton: 'Send request', urgentEyebrow: 'Direct contact', directTitle: 'For urgent issues, call now.', hoursText: '24/7 for emergency repairs.', areaText: 'Athens and suburbs.', supabaseText: 'The form keeps a clean payload for a future Supabase Edge Function email integration.', faqEyebrow: 'FAQ', faqTitle: 'Before you call', faq1Q: 'What should I do if a lot of water is running?', faq1A: 'Close the main valve if you can do so safely and call us. If there is water near electricity, avoid contact.', faq2Q: 'Can I send photos?', faq2A: 'A future Supabase connection can add uploads. For now, describe the location and we will guide you by phone.', faq3Q: 'Do you give an estimate before work?', faq3A: 'Yes. After diagnosis, we explain options and cost before repair starts.', formSuccess: 'Your request was captured locally. The next step is connecting Supabase to email the owner.'
  }
};

const menu = document.querySelector('#nav-menu');
const navToggle = document.querySelector('.nav-toggle');
const langButton = document.querySelector('[data-language-toggle]');
const savedLanguage = localStorage.getItem('siteLanguage') || 'el';

function setLanguage(language) {
  const dictionary = translations[language];
  document.documentElement.lang = language;
  document.querySelectorAll('[data-i18n]').forEach((element) => {
    const key = element.dataset.i18n;
    if (dictionary[key]) element.textContent = dictionary[key];
  });
  document.querySelectorAll('[data-i18n-aria]').forEach((element) => {
    const key = element.dataset.i18nAria;
    if (dictionary[key]) element.setAttribute('aria-label', dictionary[key]);
  });
  document.querySelectorAll('[data-language-field]').forEach((field) => { field.value = language; });
  if (langButton) langButton.textContent = language === 'el' ? 'English' : 'Ελληνικά';
  localStorage.setItem('siteLanguage', language);
}

navToggle?.addEventListener('click', () => {
  const isOpen = menu.classList.toggle('open');
  navToggle.setAttribute('aria-expanded', String(isOpen));
});

langButton?.addEventListener('click', () => {
  const nextLanguage = document.documentElement.lang === 'el' ? 'en' : 'el';
  setLanguage(nextLanguage);
});

document.querySelector('[data-contact-form]')?.addEventListener('submit', (event) => {
  event.preventDefault();
  const status = document.querySelector('[data-form-status]');
  const language = document.documentElement.lang || 'el';
  const formData = Object.fromEntries(new FormData(event.currentTarget).entries());
  console.info('Future Supabase payload:', formData);
  if (status) status.textContent = translations[language].formSuccess;
  event.currentTarget.reset();
  setLanguage(language);
});

setLanguage(savedLanguage);
